### PR TITLE
Expose Main Routing Table ID from VPC module

### PR DESCRIPTION
**Pull request by hoihrig**
Expose Main Routing Table ID from VPC module to enable using Endpoints

### CODE REVIEW

**Comment by hoihrig** [comment]
@antonbabenko @orjanaustvoldtd

**Comment by antonbabenko** [comment]
LGTM

**Comment by antonbabenko** [comment]
https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html - I don't think you need to expose main routing table id according to this doc. VPC id is enough.

**Comment by hoihrig** [comment]
Unfortunately the documentation on Terraform is out of date on that, I tried it and got an error that a routing table ID must be specified

Also doing it manually forces me to put a routing table id there.

**Comment by antonbabenko** [comment]
Ok then. Consider updating doc or at least create an issue there, if you have not done it yet.

**Comment by hoihrig** [comment]
Done.
https://github.com/hashicorp/terraform/issues/5705

**Pull request merged**
