### PR TITLE
Add a security group to talk to bastion

### PR DESCRIPTION
**Pull request by hoihrig**
Add a security group for other machines that may want to talk to bastion hosts

### CODE REVIEW

**Comment by hoihrig** [comment]
@orjanaustvoldtd

**Comment by hoihrig** [comment]
the SG: bastion is for the bastion host to accept SSH connections from the outside world to the bastion host.

the SG: ssh_from_bastion is for all other hosts that should only accept ssh from a bastion host and not any other hosts.

Logically it makes sense to create both SGs in this module

**Comment by senthuran-td** [comment]
Ok, so this "sg_from_bastion" is associated with other hosts security groups and they can only be communicated via bastion ssh? if yes then these other hosts doesn't need of SSH keys?

**Comment by hoihrig** [comment]
yes that is the case, but the other hosts will also need to have your SSH keys. This pattern is used to have better traceability on who connects to a host using SSH since there is only one way in. The purpose of Bastion hosts is to have a single easier to defend host and monitor than doing the same hardening with all hosts in your network.

Without the limitation that it is only possible to SSH from bastion hosts to your networks instances, bastion hosts are useless

**Comment by senthuran-td** [comment]
Yes, I understood bastion job, but, I didn't quite catch that you can associate security groups.
Please correct me if I'm missing something:

bastion -> SG(bastion) : open port 22 for public/internet
SG(ssh_from_bastion) -> connected to SG(bastion)
Now,
Lets take a host in public network HAPPY

HAPPY -> associated to SG (ssh_from_bastion)
At this point, this says that HAPPY can only reached via bastion?

**Comment by hoihrig** [comment]
HAPPY will be reachable by whatever SG you specify for it. But when opening it for SSH you should use SG(ssh_from_bastion) and not SG(bastion)

**Comment by senthuran-td** [comment]
Thanks for the explanation. I'll get back to you once I try this SG(ssh_from_bastion).

**Pull request merged**
